In [66]:
import pandas as pd

In [67]:
#Reading data
df = pd.read_csv('data.csv')
df.head()
#df.tail()

Fever  Myalgia  Age  Rhinorrhea  Dyspnea  Covid_Prob
0   93.284154        1    8           1       -1           0
1   96.631362        1    7           1       -1           1
2   99.984122        1   86           0       -1           0
3   95.411629        0   92           1        1           1
4  107.938645        1   56           0        0           0

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2999 entries, 0 to 2998
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Fever       2999 non-null   float64
 1   Myalgia     2999 non-null   int64  
 2   Age         2999 non-null   int64  
 3   Rhinorrhea  2999 non-null   int64  
 4   Dyspnea     2999 non-null   int64  
 5   Covid_Prob  2999 non-null   int64  
dtypes: float64(1), int64(5)
memory usage: 140.7 KB


In [69]:
df['Dyspnea'].value_counts()

-1    1029
 1    1016
 0     954
Name: Dyspnea, dtype: int64

In [70]:
df.describe()

Fever      Myalgia          Age   Rhinorrhea      Dyspnea  \
count  2999.000000  2999.000000  2999.000000  2999.000000  2999.000000   
mean    103.377591     0.510504    50.535512     0.481827    -0.004335   
std       6.140242     0.499973    28.670216     0.499753     0.825895   
min      93.018167     0.000000     1.000000     0.000000    -1.000000   
25%      98.046747     0.000000    26.000000     0.000000    -1.000000   
50%     103.228777     1.000000    50.000000     0.000000     0.000000   
75%     108.815313     1.000000    75.000000     1.000000     1.000000   
max     113.998125     1.000000   100.000000     1.000000     1.000000   

        Covid_Prob  
count  2999.000000  
mean      0.489163  
std       0.499966  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       1.000000  
max       1.000000

In [71]:
# Train Test Spliting
import numpy as np


In [72]:
def slicing(data, ratio):
    np.random.seed(1)
    # Basic slicing
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data)*ratio) # size data for the test
    test_indices = shuffled[:test_set_size] # index from row 1 up to row test-_size, the last one is exclusive
    train_indices = shuffled[test_set_size:] # index from rwo test_size to last.
    return data.iloc[train_indices], data.iloc[test_indices] # extracting rows using iloc(imaginary), instead of loc,          method when the indices are unknown.

In [73]:
train, test = slicing(df, 0.2) # 20% for test and 80% for train


In [74]:
train

Fever  Myalgia  Age  Rhinorrhea  Dyspnea  Covid_Prob
1177  107.267718        1   73           0       -1           0
268   106.873051        1   59           0        0           0
32    112.370178        1   87           0        0           0
199   108.204716        1   80           0        1           0
1382  109.415264        1   35           1        1           1
...          ...      ...  ...         ...      ...         ...
2763   96.553008        0   73           0       -1           1
905   107.538731        1   77           1       -1           0
1096   93.745437        0    4           0       -1           0
235   104.634682        0   69           0        0           1
1061  102.004200        0   90           0       -1           1

[2400 rows x 6 columns]

In [75]:
test

Fever  Myalgia  Age  Rhinorrhea  Dyspnea  Covid_Prob
2056   97.540859        0   29           1        1           0
1742   98.298742        0   39           1        1           0
2578   95.422906        1   22           1       -1           1
2100   98.816288        1   78           0        1           0
1787  112.202795        1   48           0        1           1
...          ...      ...  ...         ...      ...         ...
439   110.587563        1   12           1        0           1
2196   96.137981        1   26           1        1           0
94    113.683829        1   71           0       -1           0
2418  102.193326        1   33           0       -1           0
1413   99.005452        0   49           1       -1           1

[599 rows x 6 columns]

In [76]:
# Converting the data to numpy array
input_train = train[['Fever', 'Myalgia', 'Age', 'Rhinorrhea', 'Dyspnea']].to_numpy()
input_test = test[['Fever', 'Myalgia', 'Age', 'Rhinorrhea', 'Dyspnea']].to_numpy()
input_train

array([[107.2677175 ,   1.        ,  73.        ,   0.        ,
         -1.        ],
       [106.8730513 ,   1.        ,  59.        ,   0.        ,
          0.        ],
       [112.3701784 ,   1.        ,  87.        ,   0.        ,
          0.        ],
       ...,
       [ 93.74543741,   0.        ,   4.        ,   0.        ,
         -1.        ],
       [104.6346817 ,   0.        ,  69.        ,   0.        ,
          0.        ],
       [102.0042005 ,   0.        ,  90.        ,   0.        ,
         -1.        ]])

In [77]:
output_train = train[['Covid_Prob']].to_numpy().reshape(2400, -1)
output_test = test[['Covid_Prob']].to_numpy().reshape(599, -1)
output_train

array([[0],
       [0],
       [0],
       ...,
       [0],
       [1],
       [1]])

In [78]:
from sklearn.linear_model import LogisticRegression

In [79]:
classifier = LogisticRegression()
classifier.fit(X_train, output_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [80]:
# Predicting
feature = [100, 1, 36, -1, 1]
# Fever=100, Myalgia = yes, age=22, Rhinorrhea = yes, Dyspnea = yes
probability = classifier.predict_proba([feature]) # Returns a 2D array [a, b]. a being not having (classfier 0), b being having (classifier 1).

print(probability)
negative = probability[0][0]
positive = probability[0][1]
print(negative)
print(positive)

[[0.48847639 0.51152361]]
0.4884763892283658
0.5115236107716342
